name: Build and Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  IMAGE: nginx-proxy-manager
  MAJOR_VERSION: '2'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      build_version: ${{ steps.get_version.outputs.version }}
      branch_lower: ${{ steps.get_branch.outputs.branch_lower }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Get Version
        id: get_version
        run: echo "version=$(cat .version)" >> $GITHUB_OUTPUT
      
      - name: Get Branch Name
        id: get_branch
        run: |
          BRANCH_NAME=${{ github.head_ref || github.ref_name }}
          echo "branch_lower=$(echo $BRANCH_NAME | tr '[:upper:]' '[:lower:]' | sed 's/[\\/\\.]/-/g')" >> $GITHUB_OUTPUT

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
      
      - name: Install and Build
        run: |
          yarn install
          yarn build
          npm install
      
      - name: Update Version in Package Files
        run: |
          jq --arg v "${{ needs.setup.outputs.build_version }}" '.version = $v' frontend/package.json > tmp && mv tmp frontend/package.json
          jq --arg v "${{ needs.setup.outputs.build_version }}" '.version = $v' backend/package.json > tmp && mv tmp backend/package.json
          sed -i -E "s/(version-)[0-9]+\\.[0-9]+\\.[0-9]+(-green)/\\1${{ needs.setup.outputs.build_version }}\\2/" README.md
      
      - name: Build Frontend
        run: ./scripts/ci/frontend-build
      
      - name: Build Backend
        run: ./scripts/ci/test-and-build
      
      - name: Build Documentation
        working-directory: docs
        run: |
          yarn install
          yarn build
      
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            frontend/dist
            backend/dist
            docs/build

  test:
    needs: [setup, build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        database: [sqlite, mysql, postgres]
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Run Tests
        env:
          COMPOSE_PROJECT_NAME: npm_${{ needs.setup.outputs.branch_lower }}_${{ github.run_number }}_${{ matrix.database }}
          COMPOSE_FILE: docker/docker-compose.ci.yml:docker/docker-compose.ci.${{ matrix.database }}.yml
        run: |
          ./scripts/ci/fulltest-cypress
      
      - name: Save Debug Logs
        if: failure()
        run: |
          mkdir -p debug/${{ matrix.database }}
          docker-compose logs fullstack > debug/${{ matrix.database }}/docker_fullstack.log 2>&1
          docker-compose logs stepca > debug/${{ matrix.database }}/docker_stepca.log 2>&1
          docker-compose logs pdns > debug/${{ matrix.database }}/docker_pdns.log 2>&1
          docker-compose logs pdns-db > debug/${{ matrix.database }}/docker_pdns-db.log 2>&1
          docker-compose logs dnsrouter > debug/${{ matrix.database }}/docker_dnsrouter.log 2>&1
          
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.database }}
          path: |
            test/results/**/*
            debug/**/*
      
      - name: Cleanup
        if: always()
        run: docker-compose down --remove-orphans --volumes -t 30 || true

  docker:
    needs: [setup, test]
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set Docker Tags
        id: docker_tags
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "tags=docker.io/jc21/${IMAGE}:${{ needs.setup.outputs.build_version }},docker.io/jc21/${IMAGE}:${MAJOR_VERSION},docker.io/jc21/${IMAGE}:latest" >> $GITHUB_OUTPUT
          else
            echo "tags=docker.io/nginxproxymanager/${IMAGE}-dev:${{ needs.setup.outputs.branch_lower }}" >> $GITHUB_OUTPUT
          fi
      
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker_tags.outputs.tags }}

  docs:
    needs: [setup, docker]
    if: success() && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Docs Build
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: nginx-proxy-manager/nginx-proxy-manager-docs
          event-type: build-docs
          client-payload: '{"branch": "${{ github.ref_name }}"}'

  pr-comment:
    needs: [setup, docker]
    if: success() && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const message = `Docker Image for build ${process.env.GITHUB_RUN_NUMBER} is available on
            [DockerHub](https://cloud.docker.com/repository/docker/nginxproxymanager/${process.env.IMAGE}-dev)
            as \`nginxproxymanager/${process.env.IMAGE}-dev:${process.env.BRANCH_LOWER}\`

            **Note:** ensure you backup your NPM instance before testing this image! Especially if there are database changes
            **Note:** this is a different docker image namespace than the official image`;
            
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: message
            });
        env:
          IMAGE: ${{ env.IMAGE }}
          BRANCH_LOWER: ${{ needs.setup.outputs.branch_lower }}